### ISSUE TITLE
mqtt topic订阅 自动断开连接，导致收不到订阅

### ISSUE THREAD

**Issue by zpffly001** [blackgate/qjsMongoose#1]
**我使用qjs结合您的libqjsMongoose.so，运行js脚本连接我的mqtt broker 进行topic订阅出现了一些问题：**

qjs 运行js脚本进行mqtt消息订阅，一开始没问题。一段时间后，我再publish消息时，我的js脚本就订阅不到发送的消息了(运行你的例子没有console打印)。没有信息打印。这是我查看broker控制台，发现连接数-1，是qjs运行的js脚本已经断开了连接。为什么连接会自动断开呢？

**Comment by blackgate** [comment]
I've implemented a reconnect logic for the mqtt client, and i believe it fixes your issue. I would however advice you against using this in production. This was a toy project and is not production ready.

**Comment by zpffly001** [comment]
> I've implemented a reconnect logic for the mqtt client, and i believe it fixes your issue. I would however advice you against using this in production. This was a toy project and is not production ready.

OK, the underlying Mqtt library is ready to use the mqtt library open source by eclipse. Your code has a good reference
